[build]
  command = "npm run build"
  publish = "./dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos para forçar a limpeza de cache
[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"

# Cabeçalhos específicos para arquivos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Cabeçalhos para o service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"